paths:
  sphinx:
    command: "bunker/installed/LinuxNoEditor/UnrealApp.sh"
    level: "main_details"
    quality: "low"
    config_file: "assets/environment/config/add_mc_laren.yaml"

    firmware:
      base_command: "sphinx"
      drone_path: "/opt/parrot-sphinx/usr/share/sphinx/drones/anafi.drone"
      firmware_url: "https://firmware.parrot.com/Versions/anafi/pc/%23latest/images/anafi-pc.ext2.zip"
      pose: "-1 -1 0.3 0 -0 0.785"

  scripts:
    controller: "auto_follow/controllers/distilled_network_controller.py"
    save_dir_name: "bunker-online-4k-config-test-down-right-student"
    args:
      --log_path: "${output_dir}/logs"
      --results_path: "${output_dir}/results"
      --parquet_logs_path: "${output_dir}/parquet-logs"
