paths:
  sphinx:
    command: "/media/mihaib08/0AC68039C68026D3/models/_research_drone/bunker-cars/bunker/installed/LinuxNoEditor/UnrealApp.sh"
    level: "main_details"
    quality: "low"
    config_file: "assets/environment/config/add_mc_laren.yaml"

    firmware:
      base_command: "sphinx"
      drone_path: "/opt/parrot-sphinx/usr/share/sphinx/drones/anafi.drone"
      firmware_url: "/home/mihaib08/Desktop/_Res/drone/anafi-pc.ext2.zip"
      pose: "1 1 0.3 0 -0 3.925"

  scripts:
    controller: "auto_follow/controllers/ibvs_splitter_controller.py"
    save_dir_name: "bunker-online-4k-config-test-up-left"
